Dns-4_Celery
paktusov/parsing_dns pull request #18
Opened 2022-02-19 14:45 UTC by paktusov

shedule

2022-02-19 14:46 UTC, paktusov commented
DNS-4 tz and removed .bat

2022-02-19 14:51 UTC, z268 requested changes

2022-02-19 14:51 UTC, z268 commented on app/crawler/settings.py
> +SELENIUM_COMMAND_EXECUTOR = 'http://selenium:4444/wd/hub'
вынести бы это в конфиг и переменную окружения

2022-02-19 14:51 UTC, z268 commented on app/crawler/tasks.py
> +app.conf.timezone = 'Asia/Yekaterinburg'
тоже бы в конфиг вместе с брокером для селери

2022-02-19 14:51 UTC, z268 commented on deploy/celery/Dockerfile
> +CMD ["poetry", "run", "celery", "-A", "crawler.tasks", "worker", "-B"]
можно переиспользовать образ app (его Dockerfile), только в docker-compose переопределить команду запуска
https://docs.docker.com/compose/compose-file/compose-file-v3/#command

2022-02-19 14:51 UTC, z268 commented on app/update_notification.py
> +    now = dt.datetime.now().isoformat()
кажется теперь тут не нужно получать этот `now`, а делать это где-то внутри spider

2022-02-19 14:53 UTC, paktusov commented on app/update_notification.py
> +    now = dt.datetime.now().isoformat()
я это даже написал для себя в pipeline

2022-02-20 07:37 UTC, z268 requested changes

2022-02-20 07:37 UTC, z268 commented on app/crawler/spiders/dns.py
> +    now_time = dt.datetime.now().isoformat()
это будет выполняться во время импорта класса, а должно быть во время инициализации объекта, а еще лучше - прямо перед первым запросами.
да и в 42 строке очень похожая переменная

2022-02-20 07:37 UTC, z268 commented on app/crawler/tasks.py
> +    parsing_city(city)
в том методе 4 строки, можно было их целиком сюда перенести, а то получается зависимость от какого-то мутного файла при переименовании которого приходится вносить правки в задачу

2022-02-20 07:37 UTC, z268 commented on app/config.py
> +class SeleniumSettings(BaseSettings):
по PEP8 на верхнем уровне должны быть отступы в 2 строки между классами и функциями.
нужно будет в github actions настроить запуск линтеров, чтобы автоматически такое отлавливать )

2022-02-20 07:37 UTC, z268 commented on app/config.py
> +    worker_max_tasks_per_child = 1
не везде указана типизация. в SeleniumSetting тоже

это может быть важно, когда вместо дефолтного значения из переменной окружения у тебя придет значение и останется в виде строки `'1' `

2022-02-20 07:39 UTC, paktusov commented on app/config.py
> +    worker_max_tasks_per_child = 1
да, я уже обжегся на этом

2022-02-20 11:54 UTC, z268 commented on app/crawler/tasks.py
> +def parsing_city(city):
почти, уже близко :) но я имел ввиду положить все весь этот код из 4х строк внутрь задачи `start_parsing`.

или на эту функцию `parsing_city` навесить @app.task, но тогда нужно будет не забыть исправить имя задачи в celery beat

2022-02-20 13:27 UTC, z268 requested changes

2022-02-20 13:27 UTC, z268 commented on app/old_start_parsing.py
> +    parsing_city(args.city)
тут тоже можно было без функции обойтись) этот файл должен быть попасть в репозиторий, а то судя по названию - нет

2022-02-20 13:27 UTC, z268 commented on app/crawler/spiders/dns.py
> +        self.i = 1
переменная все еще является атрибутом класса, хотя используется только в одном месте. 
да и выносить в атрибуты класса переменную с таким названием - плохой тон.

должно быть достаточно использовать локальную переменную в `parse_result`:
```
        page_num = 1
        next_page = response.css('button.pagination-widget__show-more-btn span::text').get()
        if next_page is not None:
            page_num += 1
            next_page = f'https://www.dns-shop.ru/catalog/markdown/?p={page_num}'
```

2022-02-20 16:07 UTC, paktusov commented on app/old_start_parsing.py
> +    parsing_city(args.city)
Пока привыкаю я к celery, решил оставить

2022-02-20 16:50 UTC, z268 approved these changes

2022-02-20 17:22 UTC, merged